---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fpm
    version: v1
    app.kubernetes.io/name: fpm
  name: fpm-1
  namespace: nginx-fpm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: fpm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fpm
        version: v1
        app.kubernetes.io/name: fpm
    spec:
      containers:
      - image: php:8.2-fpm
        name: fpm
        ports:
        - containerPort: 9000
          name: tcp-fpm
        resources: {}
        volumeMounts:
          - name: fpm-config-volume
            mountPath: /usr/local/etc/php-fpm.d/www.conf
            subPath: www.conf
          - name: html-volume
            mountPath: /usr/share/nginx/html
      volumes:
        - name: fpm-config-volume
          configMap:
            name: fpm-config
        - name: html-volume
          configMap:
            name: html
status: {}
